# Generated by Django 5.2.8 on 2025-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0002_alter_service_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
