# Generated by Django 5.2.8 on 2025-11-28 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(5)),
        ),
    ]
