# Generated by Django 5.2.8 on 2025-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0006_remove_brand_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='brands', to='spartans.category'),
        ),
    ]
