# Generated by Django 5.2.8 on 2025-12-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0011_alter_product_options_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='spartans_product',
        ),
    ]
