# Generated by Django 5.2.8 on 2025-12-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0012_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
