# Generated by Django 5.2.8 on 2025-12-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0014_product_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
