# Generated by Django 5.2.8 on 2025-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0015_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, help_text='Mark as new product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(blank=True, default=False, help_text='Mark as sale product', null=True),
        ),
    ]
