# Generated by Django 5.2.8 on 2025-12-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0016_product_is_new_product_is_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
    ]
