# Generated by Django 5.2.8 on 2025-12-04 10:44

import django.db.models.deletion
import spartans.models.product_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0017_remove_product_is_new_remove_product_is_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main display image', null=True, upload_to=spartans.models.product_model.product_main_image_path),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=spartans.models.product_model.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spartans.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_image',
            },
        ),
    ]
