# Generated by Django 5.2.8 on 2025-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0019_product_is_best_seller_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
