# Generated by Django 5.2.8 on 2025-12-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0021_productreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
