# Generated by Django 5.2.8 on 2025-12-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0025_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
