# Generated by Django 5.2.8 on 2025-12-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0026_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
