# Generated by Django 5.2.8 on 2025-12-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0027_alter_cart_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
    ]
