# Generated by Django 5.2.8 on 2025-12-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0030_alter_cart_unique_together_alter_cart_table_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequestservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrequestservice',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='userrequestservice',
            name='price',
        ),
        migrations.AddField(
            model_name='userrequestservice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
