# Generated by Django 5.2.8 on 2025-12-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0030_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'checkout', 'verbose_name_plural': 'checkouts'},
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='created_at',
        ),
    ]
