# Generated by Django 5.2.8 on 2025-12-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0031_remove_userrequestservice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
