# Generated by Django 5.2.8 on 2025-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0031_remove_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrequestservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrequestservice',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='userrequestservice',
            name='price',
        ),
        migrations.AddField(
            model_name='userrequestservice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
