# Generated by Django 5.2.8 on 2025-12-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0032_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
