# Generated by Django 5.2.8 on 2025-12-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0033_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
