# Generated by Django 5.2.8 on 2025-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0033_alter_service_discription_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
