# Generated by Django 5.2.8 on 2025-12-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0034_alter_service_discription_alter_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('service_type', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spartans.service')),
            ],
            options={
                'verbose_name': 'Servicetype',
                'verbose_name_plural': 'Servicetypes',
                'db_table': 'servicetype',
            },
        ),
    ]
