# Generated by Django 5.2.8 on 2025-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0035_remove_service_discription_remove_service_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
