# Generated by Django 5.2.8 on 2025-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0036_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
