# Generated by Django 5.2.8 on 2026-01-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0037_servicetype_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
