# Generated by Django 5.2.8 on 2026-01-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0038_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='product_name',
        ),
        migrations.AddField(
            model_name='announcement',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spartans.product'),
        ),
    ]
