# Generated by Django 5.2.8 on 2026-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0039_remove_announcement_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
