# Generated by Django 5.2.8 on 2026-01-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0040_announcement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
