# Generated by Django 5.2.8 on 2026-01-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0041_remove_announcement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='main_image',
        ),
    ]
