# Generated by Django 5.2.8 on 2026-01-06 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0042_remove_announcement_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
