# Generated by Django 5.2.8 on 2026-01-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0043_rename_end_date_announcement_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='price',
        ),
    ]
