# Generated by Django 5.2.8 on 2026-01-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0044_remove_announcement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('courier', 'Moved to Courier'), ('reached_city', 'Reached City'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='shipped', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='spartans.order')),
            ],
        ),
    ]
