# Generated by Django 5.1 on 2026-01-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0045_order_order_number_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spartans.useraddress'),
        ),
    ]
