# Generated by Django 5.2.8 on 2026-01-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0046_billingaddress_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
